JPERF-1160: Assert on impacts softly
When the "improvement" case fails, it was failing on:
```
assertThat(editIssueImpact.improvement).isTrue()
assertThat(editIssueImpact.signal).isTrue()
```

The improvement assertion was red, so we didn't reach the signal
assertion. It means that we don't know if the judge thinks it's a
regression or noise. So we use soft assertions to see both checks at
once.

Using soft assertions has two consequences:
* we don't see the actual assertion line in stacktrace, so we don't know
  which boolean `isTrue` is failing, so we need the `as` string
* it doesn't workt with `satisfies`: https://github.com/assertj/assertj/issues/1353
  so we just use a local var

Before:
```
org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
...
	at com.atlassian.performance.tools.report.api.judge.RelativeNonparametricPerformanceJudgeTest$shouldJudgeImprovement$4.accept(RelativeNonparametricPerformanceJudgeTest.kt:68)
	at com.atlassian.performance.tools.report.api.judge.RelativeNonparametricPerformanceJudgeTest$shouldJudgeImprovement$4.accept(RelativeNonparametricPerformanceJudgeTest.kt:11)
	at com.atlassian.performance.tools.report.api.judge.RelativeNonparametricPerformanceJudgeTest.shouldJudgeImprovement(RelativeNonparametricPerformanceJudgeTest.kt:65)
```

After:
```
org.assertj.core.api.SoftAssertionError:
The following 2 assertions failed:
1) [improvement] expected:<[tru]e> but was:<[fals]e>
at RelativeNonparametricPerformanceJudgeTest.shouldJudgeImprovement(RelativeNonparametricPerformanceJudgeTest.java:72) expected:<[tru]e> but was:<[fals]e>
2) [signal] expected:<[tru]e> but was:<[fals]e>
at RelativeNonparametricPerformanceJudgeTest.shouldJudgeImprovement(RelativeNonparametricPerformanceJudgeTest.java:73) expected:<[tru]e> but was:<[fals]e>

	at org.assertj.core.api.SoftAssertions.assertAll(SoftAssertions.java:155)
	at com.atlassian.performance.tools.report.api.judge.RelativeNonparametricPerformanceJudgeTest.shouldJudgeImprovement(RelativeNonparametricPerformanceJudgeTest.kt:74)
```

TDD: red